/*
 * Puxcobot - A robot to play Coup in Esperanto (Puĉo)
 * Copyright (C) 2019  Neil Roberts
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "pcx-coup-help.h"

#include "pcx-text.h"

const char *
pcx_coup_help[] = {
        [PCX_TEXT_LANGUAGE_ESPERANTO] =
        "<b>RESUMO DE LA REGULOJ:</b>\n"
        "\n"
        "Puĉo estas kartludo de trompado kaj blufado. Per la roboto oni povas "
        "ludi la originalan ludon aŭ aldoni du aldonaĵojn.\n"
        "\n"
        "<b>Originala ludo</b>\n"
        "\n"
        "Ĉiu komence havas 2 kartojn (fackaŝitajn) kaj 2 monerojn. "
        "Se oni perdas vivon oni devas malkaŝi karton kaj oni ne plu povas uzi "
        "ĝin.\n"
        "\n"
        "Dum sia vico oni povas fari unu el la sekvaj agoj:\n"
        "\n"
        "<b>Enspezi</b>: gajni unu moneron kaj neniu povas malhelpi ĝin.\n"
        "\n"
        "<b>Eksterlanda helpo</b>: gajni du monerojn, sed se iu pretendas havi "
        "la dukon ri povas bloki ĝin.\n"
        "\n"
        "<b>Puĉo</b>: pagi 7 monerojn por mortigi iun. Neniu povas malhelpi "
        "tion. Se iu havas 10 monerojn ri nepre devas fari puĉon.\n"
        "\n"
        "Se oni havas unu el la sekvaj kartoj, aŭ pretendas havi ĝin, "
        "oni povas:\n"
        "\n"
        "<b>Imposto (Duko)</b>: Preni 3 monerojn.\n"
        "\n"
        "<b>Murdi (Murdisto)</b>: Pagi 3 monerojn kaj murdi iun. Se la viktimo "
        "pretendas havi la grafinon ri povas bloki ĝin.\n"
        "\n"
        "<b>Interŝanĝi (Ambasadoro)</b>: Interŝanĝi siajn kartojn por du novaj "
        "kartoj.\n"
        "\n"
        "<b>Ŝteli (Kapitano)</b>: Ŝteli 2 monerojn de alia ludanto. Se la "
        "viktimo pretendas havi la ambasadoron aŭ la kapitanon ri povas bloki "
        "ĝin.\n"
        "\n"
        "Ekzistas nur po 3 kartoj de ĉiu rolulo.\n"
        "\n"
        "Ĉiu pretendo de karto povas esti defiita de iu ajn alia ludanto. Se "
        "la defio estis prava, la defiito perdas karton, alikaze la defianto "
        "perdas karton.\n"
        "\n"
        "Tiu kiu restas vivanta venkas.\n"
        "\n"
        "<b>Inpsektista aldonaĵo</b>\n"
        "\n"
        "Se vi ludas kun ĉi tiu aldonaĵo la inspektisto anstataŭas "
        "la ambasadoron. La inspektisto povas interŝanĝi karton kaj bloki "
        "ŝteladon kiel la ambasadoro. Li ankaŭ povas:\n"
        "\n"
        "<b>Inspekti (Inspektisto)</b>: Rigardi unu karton de alia ludanto. Ri "
        "mem elektas kiun karton montri. Sekve vi povas decidi ĉu ri rajtas "
        "konservi ĝin. Se ne ri prenas novan karton.\n"
        "\n"
        "<b>Reformacia aldonaĵo</b>\n"
        "\n"
        "Kun ĉi tiu aldonaĵo, ĉiu ludanto anas en partio. Ludantoj de la sama "
        "partio ne rajtas celi unu la alian aŭ bloki la eksterlandan helpon. "
        "Ekde kiam ĉiuj restantaj ludantoj estas en la sama partio, reunuiĝo "
        "okazas kaj la limigo ne plu validas. Estas ankaŭ du pliaj agoj:\n"
        "\n"
        "<b>Konverti:</b> Ŝanĝi la partion de iu ajn ludanto, inkluzive vin "
        "mem. Konverti sin mem kostas 1 moneron, kaj aliulojn kostas 2. "
        "La mono iras al la trezorejo. Konvertado ne plu eblas post la "
        "reunuiĝo.\n"
        "\n"
        "<b>Ŝteli de la trezorejo:</b> Prentendi ne havi la dukon kaj preni "
        "la tutan monon de la trezorejo. Iu ajn rajtas defii. Tiuokaze vi "
        "devas aŭ cedi kaj perdi karton, aŭ montri ambaŭ kartojn por pruvi "
        "ke vi ne havas la dukon.",
        [PCX_TEXT_LANGUAGE_FRENCH] =
        "<b>RESUMÉ DES RÈGLES :</b>\n"
        "\n"
        "Complot est un jeu de cartes au tour du bluff. Il est possible de "
        "jouer au jeu de base ou de jouer à une combinaison de deux "
        "extensions.\n"
        "\n"
        "<b>Version originale</b>\n"
        "\n"
        "Tout le monde commence avec 2 cartes (face cachée) et 2 or. "
        "Si quelqu’un perd une vie, il doit dévoiler une carte et il ne peut "
        "plus l’utiliser.\n"
        "\n"
        "Pendant votre tour, vous pouvez faire une des actions suivantes :\n"
        "\n"
        "<b>Revenu</b> : prendre 1 or et personne ne peut l’empecher.\n"
        "\n"
        "<b>Aide étrangère</b> : prendre 2 or, mais si quelqu’un prétend avoir "
        "la duchesse il peut le bloquer.\n"
        "\n"
        "<b>Assassinat</b> : payer 7 or pour assassiner quelqu’un. Personne "
        "ne peut l’empecher. Si quelqu’un a 10 or il doit forcement faire un "
        "assassinat.\n"
        "\n"
        "Si vous avez une des cartes suivantes, ou vouz prétendez l’avoir, "
        "vous pouvez :\n"
        "\n"
        "<b>Taxer (Duchesse)</b> : Prendre 3 or.\n"
        "\n"
        "<b>Assassiner (Assassin)</b> : Payer 3 or et assassiner quelqu’un. "
        "Si la victime prétend avoir la comtesse elle peut le bloquer.\n"
        "\n"
        "<b>Échanger (Ambassadeur)</b> : Échanger vos cartes pour de nouvelles "
        "cartes.\n"
        "\n"
        "<b>Voler (Capitaine)</b> : Voler 2 or à un autre joueur. "
        "Si la victime prétend avoir l’ambassadeur ou le capitaine elle peut "
        "le bloquer.\n"
        "\n"
        "Il n’y a que trois exemplaires de chaque personnage.\n"
        "\n"
        "Chaque déclaration de carte peut être mise en doute par n’importe "
        "quel autre joueur. Si la mise en doute a raison, celui qui a été "
        "mis en doute perd une carte, sinon le metteur en doute en perd.\n"
        "\n"
        "Celui qui reste en vie remporte la partie.\n"
        "\n"
        "<b>Inquisiteur</b>\n"
        "\n"
        "Avec cette extension l’ambassedeur est remplacé par l’inquisiteur. "
        "L’inquisiteur peut échanger une carte ou bloquer le capitaine tout "
        "comme l’ambassadeur. Il peut aussi :\n"
        "\n"
        "<b>Consulter une carte (Inquisiteur)</b> : Consulter la carte d’un "
        "autre joueur. Lui-même décide à quelle carte vous montrer. Puis, "
        "vous pouvez décider s’il peut le garder. Sinon il pioche une nouvelle "
        "carte.\n"
        "\n"
        "<b>Saint-Barthélemy</b>\n"
        "\n"
        "Avec cette extension tous les joueurs ont une allégeance. Les joueurs "
        "de la même allégeance ne peuvent pas se cibler entre eux ou bloquer "
        "l’aide étrangère. Lorsque tous les joueurs ont la même allégeance, il "
        "y a une réunification et cette règle ne s’applique plus. Il y a deux "
        "actions possibles de plus :\n"
        "\n"
        "<b>Conversion</b> : Changer l’allégeance de n’importe quel jouer, "
        "y compris vous-même. Si vous vous convertez vous-même, vous payer "
        "1 pièce, sinon 2. L’argent va dans l’hospice. Cette action n’est plus "
        "permise après la réunification.\n"
        "\n"
        "<b>Détournement de fonds</b> : Prétendre ne pas avoir la duchesse "
        "et prendre tout l’argent de l’hospice. N’importe quel joueur peut "
        "vous mettre en doute. Dans ce cas, vous devez soit concéder et perdre "
        "une carte, soit montrer toutes vos cartes à fin de prouver que vous "
        "n’aviez pas la duchesse."
        "\n",
        [PCX_TEXT_LANGUAGE_ENGLISH] =
        "<b>SUMMARY OF THE RULES:</b>\n"
        "\n"
        "Coup is a bluffing card game. The bot can play the original game "
        "or any combination of two extensions.\n"
        "\n"
        "<b>Original game</b>\n"
        "\n"
        "Everybody starts with two cards (face down) and 2 coins. If someone "
        "loses a life, they have to reveal the card and they can no longer "
        "use it.\n"
        "\n"
        "On your turn, you can do one of the following actions:\n"
        "\n"
        "<b>Income</b>: Take one coin from the bank and nobody can stop you.\n"
        "\n"
        "<b>Foreign aid</b>: Take two coins, but if someone claims to have "
        "the duke they can stop you.\n"
        "\n"
        "<b>Coup</b>: Pay 7 coins to perform a coup and kill a player’s card. "
        "Nobody can prevent it. If you have 10 coins you have to choose this "
        "action.\n"
        "\n"
        "If you have one of the following cards, or just claim to have it, "
        "you can do one of these actions:\n"
        "\n"
        "<b>Tax (Duke)</b>: Take 3 coins.\n"
        "\n"
        "<b>Assassinate (Assassin)</b>: Pay 3 coins and kill someone’s card. "
        "If the target claims to have the contessa they can block it.\n"
        "\n"
        "<b>Exchange (Ambassador)</b>: Exchange your cards for new ones.\n"
        "\n"
        "<b>Steal (Captain)</b>: Take 2 coins from another player. If they "
        "claim to have the captain or the ambassador they can block it.\n"
        "\n"
        "There are only three copies of each card.\n"
        "\n"
        "Every claim of a card can be challenged by any other player. If the "
        "challenge is correct, the person who was challenged loses a card. "
        "Otherwise the challenger loses one.\n"
        "\n"
        "The winner is the last player left alive.\n"
        "\n"
        "<b>Inquisitor extension</b>\n"
        "\n"
        "If you play with the inquisitor extension, the inquisitor character "
        "replaces the ambassador. The inquisitor can exchange a card and block "
        "stealing like the ambassador. He can also:\n"
        "\n"
        "<b>Interrogate (Inquisitor)</b>: Look at a card from another player. "
        "They themselves decide which card to show you. Then you can decide "
        "whether they can keep it. If not they draw a new card.\n"
        "\n"
        "<b>Reformation extension</b>\n"
        "\n"
        "With this extension, each player is assigned an allegiance. Players "
        "in the same allegiance are not allowed to target each other or "
        "block foreign aid. Once all of the remaining players have the same "
        "allegiance, reunification occurs and the restriction no longer "
        "applies. There are also two additional actions:\n"
        "\n"
        "<b>Convert:</b> Swap the allegiance of any player, including "
        "yourself. If you convert yourself it costs 1 coin, otherwise 2. The "
        "money goes into the treasury. This action is no longer allowed "
        "after reunification.\n"
        "\n"
        "<b>Embezzle:</b> Claim to not have the duke and take all of the money "
        "in the treasury. Anybody can challenge. In that case you either have "
        "to concede and lose a card, or show both of your cards to prove that "
        "you don’t have the duke.",
        [PCX_TEXT_LANGUAGE_PT_BR] =
        "<b>RESUMO DAS REGRAS:</b>\n"
        "\n"
        "Golpe é um jogo de cartas de blefe.\n"
        "\n"
        "Todo mundo começa com duas cartas (viradas para baixo) e duas moedas. Se alguém "
        "perde uma vida, eles têm que revelar a carta e não podem mais "
        "usá-la.\n"
        "\n"
        "No seu turno, você pode realizar uma das ações a seguir:\n"
        "\n"
        "<b>Renda</b>: pegue uma moeda do banco e ninguém poderá impedir.\n"
        "\n"
        "<b>Ajuda estrangeira</b>: pegue duas moedas, mas se alguém alegar ter "
        "o duque eles podem te impedir.\n"
        "\n"
        "<b>Golpe</b>: Pague 7 moedas para realizar um golpe e matar a carta de um jogador. "
        "Ninguém conseguirá impedir. Se você tiver 10 moedas você tem que escolher essa "
        "ação.\n"
        "\n"
        "Se você tiver uma das seguintes cartas, ou apenas afirmar tê-las, "
        "você pode fazer uma destas ações:\n"
        "\n"
        "<b>Imposto (Duque)</b>: Pegue 3 moedas.\n"
        "\n"
        "<b>Assassinar (Assassino)</b>: Pague 3 moedas e mate a carta de alguém. "
        "Se o alvo alega ter a condessa, pode bloqueá-lo.\n"
        "\n"
        "<b>Troca (embaixador)</b>: troque suas cartas por novas. \n"
        "\n"
        "<b>Roubar (Capitão)</b>: Pegue 2 moedas de outro jogador. Se ele "
        "afirmar ter o capitão ou o embaixador podem bloqueá-lo.\n"
        "\n"
        "Existem apenas três cópias de cada carta.\n"
        "\n"
        "Cada afirmação de posse de carta poderá ser contestada por qualquer outro jogador. Se o "
        "desafio estiver correto, a pessoa que foi desafiada perde uma carta. "
        "Caso contrário, o desafiante perde uma.\n"
        "\n"
        "O vencedor é o último jogador restante. ",
};
